// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/kv/kv.proto

package kv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status codes for KV RPC responses.
// Using an enum keeps RPC semantics explicit and extensible.
type Status int32

const (
	Status_STATUS_OK        Status = 0
	Status_STATUS_NOT_FOUND Status = 1
	Status_STATUS_ERROR     Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_OK",
		1: "STATUS_NOT_FOUND",
		2: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_OK":        0,
		"STATUS_NOT_FOUND": 1,
		"STATUS_ERROR":     2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kv_kv_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_kv_kv_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_kv_kv_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_kv_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=kv.Status" json:"status,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_kv_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_OK
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_kv_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=kv.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_kv_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_OK
}

func (x *PutResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_proto_kv_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_kv_proto_rawDescGZIP(), []int{4}
}

func (x *AppendRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AppendRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AppendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=kv.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_proto_kv_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_kv_proto_rawDescGZIP(), []int{5}
}

func (x *AppendResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_OK
}

func (x *AppendResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_kv_kv_proto protoreflect.FileDescriptor

const file_proto_kv_kv_proto_rawDesc = "" +
	"\n" +
	"\x11proto/kv/kv.proto\x12\x02kv\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"l\n" +
	"\vGetResponse\x12\"\n" +
	"\x06status\x18\x01 \x01(\x0e2\n" +
	".kv.StatusR\x06status\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"S\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"V\n" +
	"\vPutResponse\x12\"\n" +
	"\x06status\x18\x01 \x01(\x0e2\n" +
	".kv.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"V\n" +
	"\rAppendRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"Y\n" +
	"\x0eAppendResponse\x12\"\n" +
	"\x06status\x18\x01 \x01(\x0e2\n" +
	".kv.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage*?\n" +
	"\x06Status\x12\r\n" +
	"\tSTATUS_OK\x10\x00\x12\x14\n" +
	"\x10STATUS_NOT_FOUND\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x022\x92\x01\n" +
	"\tKvService\x12(\n" +
	"\x03Get\x12\x0e.kv.GetRequest\x1a\x0f.kv.GetResponse\"\x00\x12(\n" +
	"\x03Put\x12\x0e.kv.PutRequest\x1a\x0f.kv.PutResponse\"\x00\x121\n" +
	"\x06Append\x12\x11.kv.AppendRequest\x1a\x12.kv.AppendResponse\"\x00B8Z6github.com/imPranav14/Distributed-KV-Store/proto/kv;kvb\x06proto3"

var (
	file_proto_kv_kv_proto_rawDescOnce sync.Once
	file_proto_kv_kv_proto_rawDescData []byte
)

func file_proto_kv_kv_proto_rawDescGZIP() []byte {
	file_proto_kv_kv_proto_rawDescOnce.Do(func() {
		file_proto_kv_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kv_kv_proto_rawDesc), len(file_proto_kv_kv_proto_rawDesc)))
	})
	return file_proto_kv_kv_proto_rawDescData
}

var file_proto_kv_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kv_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_kv_kv_proto_goTypes = []any{
	(Status)(0),            // 0: kv.Status
	(*GetRequest)(nil),     // 1: kv.GetRequest
	(*GetResponse)(nil),    // 2: kv.GetResponse
	(*PutRequest)(nil),     // 3: kv.PutRequest
	(*PutResponse)(nil),    // 4: kv.PutResponse
	(*AppendRequest)(nil),  // 5: kv.AppendRequest
	(*AppendResponse)(nil), // 6: kv.AppendResponse
}
var file_proto_kv_kv_proto_depIdxs = []int32{
	0, // 0: kv.GetResponse.status:type_name -> kv.Status
	0, // 1: kv.PutResponse.status:type_name -> kv.Status
	0, // 2: kv.AppendResponse.status:type_name -> kv.Status
	1, // 3: kv.KvService.Get:input_type -> kv.GetRequest
	3, // 4: kv.KvService.Put:input_type -> kv.PutRequest
	5, // 5: kv.KvService.Append:input_type -> kv.AppendRequest
	2, // 6: kv.KvService.Get:output_type -> kv.GetResponse
	4, // 7: kv.KvService.Put:output_type -> kv.PutResponse
	6, // 8: kv.KvService.Append:output_type -> kv.AppendResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_kv_kv_proto_init() }
func file_proto_kv_kv_proto_init() {
	if File_proto_kv_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kv_kv_proto_rawDesc), len(file_proto_kv_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kv_kv_proto_goTypes,
		DependencyIndexes: file_proto_kv_kv_proto_depIdxs,
		EnumInfos:         file_proto_kv_kv_proto_enumTypes,
		MessageInfos:      file_proto_kv_kv_proto_msgTypes,
	}.Build()
	File_proto_kv_kv_proto = out.File
	file_proto_kv_kv_proto_goTypes = nil
	file_proto_kv_kv_proto_depIdxs = nil
}
